### ISSUE TITLE
Gmin greater than 1

### ISSUE THREAD

**Issue by iamTad** [genevalab/POPBAMTools#1]
Hi,

I'm running POPBAMTools on a POPBAM run with 3 drosophila species (A has 2 samples, B has 9 samples, and C has 5 samples). When I obtain my data and run calc_gmin() in R, samples B and C have Gmin values of around 4 to 4.5 across a chromosome. I thought that the values can only range from 0 to 1. Is there a reason why my results might be pretty wonky? The other pairwise comparisons yield more appropriate values.

Best.

**Comment by geneva** [comment]
I suspect your POPBAM output is getting parsed incorrectly as Gmin shouldn’t ever be greater than 1. Can you send me a small portion of your R output so I can try to replicate the issue?

**Comment by iamTad** [comment]
Hi Geneva,

Certainly! I've attached a small portion of my POPBAM output (popbamout*txt) and the resulting R output (gmin*txt)
[gmin_3pop.txt](https://github.com/geneva/POPBAMTools/files/3365070/gmin_3pop.txt)
[popbamout_3pop.txt](https://github.com/geneva/POPBAMTools/files/3365071/popbamout_3pop.txt)

. I'd also like to mention that a workaround that gave me proper values is to run POPBAM on 3 different bam files--one for each pairwise comparison.

**Comment by geneva** [comment]
Thank you for sending the files. First, I am happy to hear that you were able to get reasonable values by making 3 separate bam files. We typically ran POPBAM in a similar manner and I believe what you have discovered is a bug in POPBAM, and not the POPBAMTools R package. Unfortunately, the POPBAM program is not being actively developed, so I am not sure if there will be a fix released. That said, POPBAM was throughly tested for paired datasets and I am confident the results you got from using three separate, pairwise comparisons are accurate.
